version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "06:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - cheshirekate8
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
  - dependency-name: cypress
    versions:
    - 6.3.0
