name: CI
on: pull_request

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install and run CI
      run: |
        yarn
        yarn run ci
        