name: CI
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install and run CI
      run: |
        yarn policies set-version 3.1.1
        yarn
        yarn run ci
        