name: Run CI on dolthub-cypress
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install and run CI
      run: |
        yarn
        yarn run ci
    - name: Run Cypress tests against dolthub prod
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true
      env: 
        CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
        CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}