  name: Run all Cypress tests
  on: 
    schedule:
      # run every hour during business hours (UTC time)
      - cron: '0 0,16-23 * * 1-5'
      # run every 3 hours outside of business hours
      - cron: '0 1-15/3 * * 1-5'
      # run every 3 hours on weekends
      - cron: '0 */3 * * 6,0'
  jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
