name: Tests (DoltHub Dev)
on: 
  workflow_dispatch:
    inputs:
      preview:
        description: 'Choose a dev or dev preview'
        required: true
        default: 'dolthub'
        type: choice
        options:
        - dolthub
        - dolthub-preview-1
        - dolthub-preview-2
        - dolthub-preview-3

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          config-file: cypress.config.ts
        env:
          CYPRESS_BASE_URL: https://${{ github.event.inputs.preview }}.awsdev.ld-corp.com
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
      - name: Save screenshots of failed tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7
