name: Tests Blog (Dev)
on:
  workflow_dispatch:
  schedule:
    # run once per day at 9am PST (5pm UTC)
    - cron: "0 17 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: yarn
      - name: Cypress run blog tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          config-file: cypress.blog.config.js
        env:
          CYPRESS_BASE_URL: https://dolthub.awsdev.ld-corp.com
      - name: Save screenshots of failed tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7
