  name: Run Cypress tests against DoltHub dev
  on: 
    workflow_dispatch:
      inputs:
        service:
          description: 'name of service to deploy'
          required: true
  jobs:
    service-name:
      name: Set Service Name
      runs-on: ubuntu-18.04
      outputs:
        service: ${{ steps.set-service-name.outputs.service }}
      steps:
      - id: set-service-name
        working-directory: ./.github/scripts
        run: |
          ./set-service-name.sh "$SERVICE"
        env:
          SERVICE: ${{ github.event.inputs.service }}
    cypress-base-url-name:
      name: Set Cypress Base URL
      needs: service-name
      runs-on: ubuntu-18.04
      outputs:
        service: ${{ steps.set-cypress-base-url.outputs.cypress_base_url }}
      steps:
      - id: set-cypress-base-url
        run: |
          service="$SERVICE"
          cypress_base_url="https://dolthub.awsdev.ld-corp.com"
          if [ "$SERVICE" == "dolthub-v3" ]; then
            cypress_base_url="https://dolthub-v3.awsdev.ld-corp.com"
          fi
          echo "::set-output name=cypress_base_url::$cypress_base_url"
        env:
          SERVICE: ${{ needs.service-name.outputs.service }}

    cypress-run:
      runs-on: ubuntu-latest
      needs: set-cypress-base-url
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        env:
          CYPRESS_BASE_URL: ${{ steps.set-cypress-base-url.outputs.cypress_base_url }}
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
