  name: Tests (DoltHub Prod)
  on: 
    schedule:
      # run every hour during business hours (UTC time)
      - cron: '0 0,16-23 * * 1-5'
      # run every 3 hours outside of business hours
      - cron: '0 1-15/3 * * 1-5'
      # run every 3 hours on weekends
      - cron: '0 */3 * * 6,0'
    pull_request:
      branches:
        - main
  jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          headless: true
        env: 
          CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
          CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
